version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PYGDA_DB_NAME}
      POSTGRES_USER: ${PYGDA_DB_USER}
      POSTGRES_PASSWORD: ${PYGDA_DB_PASS}
    ports:
    - 22222:5432
